version: '3.8'

services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_DB: cvwo24
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - localNetwork
    ports:
      - 5432:5432

  backend:
    build: ./server-backend
    networks:
      - localNetwork
    ports:
      - 8000:8000
    depends_on:
      - "database"
      # setup the environment variables here if using docker container
    environment:
      PORT: 8000
      DATABASE_URL: "host=database user=postgres password=root dbname=cvwo24 port=5432 sslmode=disable"
      SECRET_KEY: YOUR_SECRET_KEY
      FRONTEND_URL_1: http://localhost:5173
      FRONTEND_URL_2: http://localhost:5173/

  frontend:
    build: ./client-frontend
    networks:
      - localNetwork
    ports:
      - 5173:5173
    depends_on:
      - "backend"
    # setup the environment variables here if using docker container
    environment:
      VITE_REACT_APP_API_URL: http://localhost:8000/api/
      VITE_REACT_APP_URL: http://localhost:5173

networks:
  localNetwork:
